from typing import Mapping, Optional, Sequence, Union

from .authoring import MovementRule

PropertyValue = Union[bool, int, str]


class EntityHandle:
    @property
    def index(self) -> int: ...
    @property
    def generation(self) -> int: ...
    @property
    def packed(self) -> int: ...


class SpaceHandle:
    @property
    def index(self) -> int: ...
    @property
    def generation(self) -> int: ...
    @property
    def packed(self) -> int: ...


class PlayerHandle:
    @property
    def index(self) -> int: ...
    @property
    def generation(self) -> int: ...
    @property
    def packed(self) -> int: ...


class ActionHandle:
    @property
    def value(self) -> int: ...


class EntityView:
    entity: EntityHandle
    location: Optional[SpaceHandle]
    owner: Optional[PlayerHandle]
    tag_ids: Sequence[int]


class MoveCandidate:
    @property
    def destination(self) -> SpaceHandle: ...
    @property
    def capture(self) -> Optional[EntityHandle]: ...


class DiceResult:
    stream: str
    expression: str
    dice: Sequence[int]
    total: int


class RuleProgram:
    @property
    def hash(self) -> int: ...
    @property
    def instruction_count(self) -> int: ...
    @property
    def direction_count(self) -> int: ...


class RuleContext:
    @property
    def action(self) -> ActionHandle: ...
    @property
    def issuer(self) -> PlayerHandle: ...
    @property
    def actor(self) -> Optional[EntityHandle]: ...
    @property
    def targets(self) -> Sequence[Union[EntityHandle, SpaceHandle, PlayerHandle]]: ...
    def entity(self, entity: EntityHandle) -> EntityView: ...
    def entities_at(self, space: SpaceHandle) -> Sequence[EntityHandle]: ...
    def neighbors(self, space: SpaceHandle, direction: str) -> Sequence[SpaceHandle]: ...
    def property(self, entity: EntityHandle, name: str) -> Optional[PropertyValue]: ...
    def has_tag(self, entity: EntityHandle, name: str) -> bool: ...
    def argument(self, name: str) -> Optional[PropertyValue]: ...
    def evaluate_movement(
        self, actor: EntityHandle, program: RuleProgram
    ) -> Sequence[MoveCandidate]: ...


class Transaction:
    def move(self, entity: EntityHandle, destination: Optional[SpaceHandle]) -> None: ...
    def destroy(self, entity: EntityHandle) -> None: ...
    def set_owner(self, entity: EntityHandle, owner: Optional[PlayerHandle]) -> None: ...
    def spawn(
        self,
        location: Optional[SpaceHandle] = ...,
        owner: Optional[PlayerHandle] = ...,
        tags: Sequence[str] = ...,
        properties: Mapping[str, PropertyValue] = ...,
    ) -> EntityHandle: ...
    def set_property(self, entity: EntityHandle, name: str, value: PropertyValue) -> None: ...
    def erase_property(self, entity: EntityHandle, name: str) -> None: ...
    def add_tag(self, entity: EntityHandle, name: str) -> None: ...
    def remove_tag(self, entity: EntityHandle, name: str) -> None: ...
    def roll(self, expression: str, stream: str) -> DiceResult: ...


def compile_movement(rule: MovementRule, direction_ids: Mapping[str, int]) -> RuleProgram: ...
